import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Follow actual content; the upstream template includes empty framework folders.
const sidebars: SidebarsConfig = {
  course: [{type: 'autogenerated', dirName: '.'}],
};
export default sidebars;
